# Site settings
title: Tech6
email: alunje73@gmail.com
description: We're building something cool and would like to keep you updated and in the loop. <br> If you're interested kindly join our mailing list and we'll let you know when Tech6 will be ready for testing
baseurl: "/tech6/" # the subpath of your site, e.g. /blog
url: "stephenajulu.com" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
